version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn personal_cloud_project.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 60
    volumes:
      - media_volume:/app/media
      - static_volume:/app/staticfiles
    expose:
      - "8000"
    environment:
      - DEBUG=${DEBUG:-False}
      - DJANGO_SETTINGS_MODULE=personal_cloud_project.settings
      - SECRET_KEY=${SECRET_KEY}
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - media_volume:/app/media:ro
      - static_volume:/app/staticfiles:ro
    depends_on:
      - web
    restart: always

volumes:
  media_volume:
  static_volume: